### ISSUE TITLE
NullPointerException from MavenPomReader

### ISSUE THREAD

**Issue by jomrazek** [Commonjava/cartographer#90]
input data into MavenPomReader.read(ref, locations):
-org.jboss.pnc:build-agent:0.1.4-SNAPSHOT
-[SimpleLocation [uri=file:/tmp/deps5729229400137137220], SimpleLocation [uri=http://repo.maven.apache.org/maven2/], SimpleLocation [uri=https://repository.jboss.org/nexus/content/repositories/snapshots], SimpleLocation [uri=https://oss.sonatype.org/content/repositories/snapshots/], SimpleLocation [uri=http://dl.bintray.com/rnc/maven]]

we get:
```
java.lang.NullPointerException
org.commonjava.maven.galley.maven.parse.MavenMetadataReader.getMetadata(MavenMetadataReader.java:110)
org.commonjava.maven.galley.maven.internal.version.VersionResolverImpl.resolveFirstSnapshotRefWithLocation(VersionResolverImpl.java:293)
org.commonjava.maven.galley.maven.internal.version.VersionResolverImpl.resolveFirstMatchVariableVersionLocation(VersionResolverImpl.java:181)
org.commonjava.maven.galley.maven.internal.ArtifactManagerImpl.resolveSingleVariableVersion(ArtifactManagerImpl.java:473)
org.commonjava.maven.galley.maven.internal.ArtifactManagerImpl.resolveFirstVirtualResource(ArtifactManagerImpl.java:457)
org.commonjava.maven.galley.maven.internal.ArtifactManagerImpl.retrieveFirst(ArtifactManagerImpl.java:200)
org.commonjava.maven.galley.maven.parse.MavenPomReader.getDocRef(MavenPomReader.java:199)
org.commonjava.maven.galley.maven.parse.MavenPomReader.read(MavenPomReader.java:318)
org.commonjava.maven.galley.maven.parse.MavenPomReader.read(MavenPomReader.java:302)
org.commonjava.maven.galley.maven.parse.MavenPomReader.read(MavenPomReader.java:288)
org.jboss.da.communication.pom.PomAnalyzerImpl.getDiscoveryResult(PomAnalyzerImpl.java:191)
```

**Comment by thescouser89** [comment]
Also hitting the same bug when we are trying to analyze PNC master.

It seems galley doesn't like SNAPSHOT versions?

**Comment by jdcasey** [comment]
I think this is related to all the nulls returned in CartographerProducer, but I need a targeted unit test in DA code to pursue it. There are too many guesses to be made if I simply set something up directly in galley to check this.
